name: CI

on:
  pull_request:
    branches:
      - main

# only allow one CI workflow at a time per ref to be running
concurrency:
  group: actions-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    uses: coreeng/p2p/.github/workflows/platform-release.yaml@main
    with:
      registry: ghcr.io
      image_name: ${{ github.repository }}
      image_description: "Core Platform"

  matrix:
    name: Matrix
    needs:
      - release
    uses: coreeng/p2p/.github/workflows/platform-environment-matrix.yaml@main
    with:
      include_release: false

  validate:
    name: Validate
    uses: ./.github/workflows/validate.yaml
    with:
      action: validate

  ci:
    name: CI
    needs:
      - release
      - matrix
    uses: coreeng/p2p/.github/workflows/platform-ci.yaml@main
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    with:
      environment: ${{ matrix.environment }}
      platform: ${{ matrix.platform }}
      release: ${{ needs.release.outputs.version }}@${{ needs.release.outputs.digest }}
      release_build: true
    secrets:
      cecg-registry-username: ${{ secrets.CECG_DOCKER_USERNAME }}
      cecg-registry-secret: ${{ secrets.CECG_DOCKER_SECRET }}
