name: Release

on:
  push:
    tags:
      - 'v*'

# only allow one Release workflow at a time per ref to be running
concurrency:
  group: actions-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    uses: coreeng/p2p/.github/workflows/platform-release.yaml@main
    with:
      registry: ghcr.io
      image_name: ${{ github.repository }}
      image_description: "Core Platform"
